In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
boston = pd.read_csv('data_boston.csv')
census = pd.read_csv('data_census.csv')
coffee = pd.read_csv('data_coffeeshop.csv')
sales = pd.read_csv('data_sales.csv')
studentlist = pd.read_csv('data_studentlist.csv')

In [3]:
boston

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [4]:
census

,Province Code,City Code,Population,Households,Person's Household,Gender Ratio
0,109,1001,"10,078,850","4,197,478",2.40,0.97
1,109,1188,"155,695","72,882",2.14,0.98
2,109,1189,"126,817","59,614",2.13,1.00
3,109,1158,"235,186","108,138",2.17,0.94
4,109,1105,"298,145","126,915",2.35,0.99
...,...,...,...,...,...,...
276,103,1011,"63,069","27,724",2.27,0.94
277,103,1233,"48,856","24,193",2.02,0.91
278,115,1001,"615,250","251,478",2.45,1.01
279,115,1186,"454,673","182,709",2.49,1.00
280,115,1096,"160,577","68,769",2.34,1.02

In [5]:
coffee

       Year of Start Current State  Size of Site
0             2008.0            In         20.80
1             2010.0            In        212.72
2             2013.0            In         20.04
3             2012.0            In         64.17
4             2002.0           Out         11.40
...              ...           ...           ...
43177         2014.0           Out         30.61
43178         2011.0            In         44.21
43179         2013.0            In         35.70
43180         2011.0           Out         46.20
43181         2014.0            In        176.49

[43182 rows x 3 columns]

In [6]:
sales

         Date   Region     Item  Unit Price  Units
0   04-Jul-14     East  Pen Set        4.99     62
1   12-Jul-14     East   Binder        1.99     29
2   21-Jul-14  Central  Pen Set       12.49     55
3   29-Jul-14     East   Binder       19.99     81
4   07-Aug-14  Central  Pen Set       23.95     42
5   15-Aug-14     East   Pencil        4.99     35
6   24-Aug-14     West     Desk      275.00      3
7   01-Sep-14  Central     Desk      125.00      2
8   10-Sep-14  Central   Pencil        1.29      7
9   18-Sep-14     East  Pen Set       15.99     16
10  27-Sep-14     West      Pen        1.99     76
11  05-Oct-14  Central   Binder        8.99     28
12  14-Oct-14     West   Binder       19.99     57
13  22-Oct-14     East      Pen        8.99     64
14  31-Oct-14  Central   Pencil        1.29     14
15  08-Nov-14     East      Pen       19.99     15
16  17-Nov-14  Central   Binder        4.99     11
17  25-Nov-14  Central  Pen Set        4.99     96
18  04-Dec-14  Central   Binder       19.99     94
19  12-Dec-14  Central   Pencil        1.29     67
20  21-Dec-14  Central   Binder        4.99     28
21  29-Dec-14     East  Pen Set       15.99     74
22  06-Jan-15     East   Pencil        1.99     95
23  15-Jan-15  Central   Binder        8.99     46
24  23-Jan-15  Central   Binder       19.99     50
25  01-Feb-15  Central   Binder       15.00     87
26  09-Feb-15  Central   Pencil        4.99     36
27  18-Feb-15     East   Binder        4.99      4
28  26-Feb-15  Central      Pen       19.99     27
29  07-Mar-15     West   Binder       19.99      7
30  15-Mar-15     West   Pencil        2.99     56
31  24-Mar-15  Central  Pen Set        4.99     50
32  01-Apr-15     East   Binder        4.99     60
33  10-Apr-15  Central   Pencil        1.99     66
34  18-Apr-15  Central   Pencil        1.99     75
35  27-Apr-15     East      Pen        4.99     96
36  05-May-15  Central   Pencil        4.99     90
37  14-May-15  Central   Pencil        1.29     53
38  22-May-15     West   Pencil        1.99     32
39  31-May-15  Central   Binder        8.99     80
40  08-Jun-15     East   Binder        8.99     60
41  17-Jun-15  Central     Desk      125.00      5
42  25-Jun-15  Central   Pencil        4.99     90

In [7]:
studentlist

                Name Gender  Age  Grade Absence Bloodtype  Height  Weight
0      Jared Diamond      M   23      3       Y         O   165.3    68.2
1     Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2       Brian Martin      M   24      4       N         B   175.0    80.1
3       David Hassel      M   23      3       N        AB   182.1    85.7
4    Clara Rodriquez      F   20      1       Y         A   168.0    49.5
5   Jennifer Lorentz      F   21      2       N         O   162.0    52.0
6        Susan Clark      F   22      1       N         O   155.2    45.3
7    Margareth Jones      F   23      1       N         A   176.9    55.0
8       John Bertsch      M   23      3       N         B   178.5    64.2
9     Jake Timmerman      M   22      2       N         B   176.1    61.3
10     Joshua Connor      M   24      4       Y         O   167.1    62.0
11      John Matsuda      M   22      2       N        AB   180.0    75.8
12      Eddy Johnson      M   21      1       N         A   162.2    55.3
13  Rebecah Anderson      F   23      3       N         O   176.1    53.1
14      Linda Carter      F   22      2       N         B   158.2    45.2
15    Richard Swayze      M   24      4       Y         B   168.6    70.2
16       Andrew King      M   21      1       N         A   169.2    62.2