In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st

In [2]:
df = pd.read_csv('data_studentlist.csv', header='infer', encoding='latin1')

In [3]:
df

                name gender  age  grade absence bloodtype  height  weight
0      Jared Diamond      M   23      3       Y         O   165.3    68.2
1     Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2       Brian Martin      M   24      4       N         B   175.0    80.1
3       David Hassel      M   23      3       N        AB   182.1    85.7
4    Clara Rodriquez      F   20      1       Y         A   168.0    49.5
5   Jennifer Lorentz      F   21      2       N         O   162.0    52.0
6        Susan Clark      F   22      1       N         O   155.2    45.3
7    Margareth Jones      F   23      1       N         A   176.9    55.0
8       John Bertsch      M   23      3       N         B   178.5    64.2
9     Jake Timmerman      M   22      2       N         B   176.1    61.3
10     Joshua Connor      M   24      4       Y         O   167.1    62.0
11      John Matsuda      M   22      2       N        AB   180.0    75.8
12      Eddy Johnson      M   21      1       N         A   162.2    55.3
13  Rebecah Anderson      F   23      3       N         O   176.1    53.1
14      Linda Carter      F   22      2       N         B   158.2    45.2
15    Richard Swayze      M   24      4       Y         B   168.6    70.2
16       Andrew King      M   21      1       N         A   169.2    62.2

In [4]:
bloodType = df['bloodtype']
gender = df['gender']

In [5]:
bloodType.value_counts()

bloodtype
O     5
B     5
A     4
AB    3
Name: count, dtype: int64

In [6]:
gender.value_counts()

gender
M    10
F     7
Name: count, dtype: int64

In [7]:
bloodType.value_counts()/bloodType.size

bloodtype
O     0.294118
B     0.294118
A     0.235294
AB    0.176471
Name: count, dtype: float64

In [8]:
gender.value_counts()/gender.size

gender
M    0.588235
F    0.411765
Name: count, dtype: float64

In [9]:
# contingency table
pd.crosstab(bloodType, gender)

gender     F  M
bloodtype
A          2  2
AB         1  2
B          1  4
O          3  2

In [10]:
pd.crosstab(bloodType, gender,margins=True)

gender     F   M  All
bloodtype
A          2   2    4
AB         1   2    3
B          1   4    5
O          3   2    5
All        7  10   17

In [11]:
data = np.array([220,215,93,64])
eye = pd.Series(data, index=['Brown', 'Blue', 'Hazel','Green'])
eye

Brown    220
Blue     215
Hazel     93
Green     64
dtype: int64

In [12]:
eye/eye.sum()

Brown    0.371622
Blue     0.363176
Hazel    0.157095
Green    0.108108
dtype: float64

In [13]:
st.chisquare(eye)

Power_divergenceResult(statistic=np.float64(133.47297297297297), pvalue=np.float64(9.650879774148268e-29))

In [14]:
my_model = len(eye)*[np.mean(eye)]
st.chisquare(f_obs=eye,f_exp = my_model)

Power_divergenceResult(statistic=np.float64(133.47297297297297), pvalue=np.float64(9.650879774148268e-29))

In [16]:
my_model = eye.sum()*np.array([0.4,0.33,0.15,0.12])
st.chisquare(f_obs=eye,f_exp = my_model)

Power_divergenceResult(statistic=np.float64(4.06265356265356), pvalue=np.float64(0.25477767063672113))

In [17]:
data_eye = {'Brown': [68,119,26,7], 'Blue':[20,84,17,94], 'Hazel':[15,54,14,10], 'Green':[5,29,14,16]}
data = pd.DataFrame(data_eye,index=['Blue','Brown','Red','Blonde'])
data

        Brown  Blue  Hazel  Green
Blue       68    20     15      5
Brown     119    84     54     29
Red        26    17     14     14
Blonde      7    94     10     16

In [18]:
st.chi2_contingency(data)

Chi2ContingencyResult(statistic=np.float64(138.28984162600824), pvalue=np.float64(2.325286787098839e-25), dof=9, expected_freq=array([[ 40.13513514,  39.22297297,  16.96621622,  11.67567568],
       [106.28378378, 103.86824324,  44.92905405,  30.91891892],
       [ 26.38513514,  25.78547297,  11.15371622,   7.67567568],
       [ 47.19594595,  46.12331081,  19.95101351,  13.72972973]]))

In [19]:
data_survived = {'Yes':[122,167,528,673], 'No':[203,118,178,212]}
data = pd.DataFrame(data_survived, index=['1st', '2nd', '3rd','Crew'])
data

      Yes   No
1st   122  203
2nd   167  118
3rd   528  178
Crew  673  212

In [20]:
st.chi2_contingency(data)

Chi2ContingencyResult(statistic=np.float64(190.40110361683327), pvalue=np.float64(4.999927529868003e-41), dof=3, expected_freq=array([[220.01363017, 104.98636983],
       [192.93502953,  92.06497047],
       [477.93730123, 228.06269877],
       [599.11403907, 285.88596093]]))

In [21]:
np.random.seed(1234)
n=20
mu=10
sigma=2
x = np.random.randn(n)*sigma + mu
ssq = x.var(ddof=1)

In [22]:
sigma0sq = 2**2
test_stat = (n-1)*ssq/sigma0sq
print("Test statistic: %f" % test_stat)
acceptance_range = {'low': st.chi2.ppf(0.025,n-1), 'high': st.chi2.ppf(0.975,n-1)}
acceptance_range

Test statistic: 23.067557

{'low': np.float64(8.906516481987971), 'high': np.float64(32.85232686172969)}

In [24]:
p_value1 = 1 - st.chi2.cdf(test_stat, n-1)
p_value1

np.float64(0.23437934469820776)

In [25]:
p_value2 = st.chi2.cdf(test_stat, n-1)

In [26]:
p_value2

np.float64(0.7656206553017922)

In [27]:
p_value3 = 2*p_value1

In [28]:
p_value3

np.float64(0.4687586893964155)

In [29]:
np.random.seed(1234)
n1 = 25
n2 = 20
n3 = 30

x1 = np.random.randn(n1)*2 + 10
x2 = np.random.randn(n2)*4 - 5
x3 = np.random.randn(n3)*2 + 50
ssq_1 = x1.var(ddof=1)
ssq_2 = x2.var(ddof=2)
ssq_3 = x3.var(ddof=3)

In [31]:
print("s1^2 = ",ssq_1)
print("s2^2 = ",ssq_2)
print("s3^2 = ",ssq_3)

s1^2 =  4.26404149266908
s2^2 =  17.073168321927582
s3^2 =  3.8065053570926306

In [33]:
test_stat = ssq_2/ssq_1
p_value = 2*(1-st.f.cdf(test_stat, n2-1, n1-1))
p_value

np.float64(0.0017013526882414531)

In [34]:
p_value = 1 - st.f.cdf(test_stat, n2-1, n1-1)
p_value

np.float64(0.0008506763441207266)

In [35]:
test_stat = ssq_1/ssq_3
p_value = 2*(1-st.f.cdf(test_stat, n1-1, n3-1))
p_value

np.float64(0.7635021244976743)

In [36]:
test_stat = ssq_1/ssq_3
p_value = (1-st.f.cdf(test_stat, n1-1, n3-1))
p_value

np.float64(0.38175106224883715)

In [ ]:
test_stat