In [1]:
import numpy as np

In [2]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
x = np.array(['Male','Female','Male', 'Male', 'Female','Female','Female'])
y = pd.Series(x)

In [6]:
y

0      Male
1    Female
2      Male
3      Male
4    Female
5    Female
6    Female
dtype: object

In [7]:
type(y)

pandas.core.series.Series

In [13]:
a = pd.Series({'a': 1, 'b': 2, 'c': 3})

In [14]:
a

a    1
b    2
c    3
dtype: int64

In [26]:
a.values

array([1, 2, 3], dtype=int64)

In [27]:
a[chr(97)]

1

In [28]:
list_data = ['2019-01-02', 3.14, 'ABC', True]
ser2 = pd.Series(list_data)

In [29]:
ser2

0    2019-01-02
1          3.14
2           ABC
3          True
dtype: object

In [30]:
ser2.index

RangeIndex(start=0, stop=4, step=1)

In [34]:
df = pd.DataFrame({
    "Name": ['Alex', 'Bonny', 'Charlie'],
    'Age': [22, 35, 58],
    'Sex':['Male' if i%2==0 else 'Female' for i in range(3)]
})

In [36]:
type(df['Age'])

pandas.core.series.Series

In [38]:
g = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7,8,9]])

In [39]:
g.columns

RangeIndex(start=0, stop=3, step=1)

In [46]:
g[[0]]

   0
0  1
1  4
2  7

In [49]:
g[0]

0    1
1    4
2    7
Name: 0, dtype: int64

In [50]:
df

      Name  Age     Sex
0     Alex   22    Male
1    Bonny   35  Female
2  Charlie   58    Male

<bound method NDFrame.first of       Name  Age     Sex
0     Alex   22    Male
1    Bonny   35  Female
2  Charlie   58    Male>